// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.Data;

namespace StarWars.Data.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    [Migration("20200728173241_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarWars.Domain.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Luke Skywalker"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Darth Vader"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Han Solo"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Leia Organa"
                        },
                        new
                        {
                            Id = 5,
                            Name = "C-3PO"
                        },
                        new
                        {
                            Id = 6,
                            Name = "R2-D2"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wilhuff Tarkin"
                        });
                });

            modelBuilder.Entity("StarWars.Domain.CharacterEpisode", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "EpisodeId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("CharacterEpisode");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            EpisodeId = 1
                        },
                        new
                        {
                            CharacterId = 1,
                            EpisodeId = 2
                        },
                        new
                        {
                            CharacterId = 1,
                            EpisodeId = 3
                        },
                        new
                        {
                            CharacterId = 2,
                            EpisodeId = 1
                        },
                        new
                        {
                            CharacterId = 2,
                            EpisodeId = 2
                        },
                        new
                        {
                            CharacterId = 2,
                            EpisodeId = 3
                        },
                        new
                        {
                            CharacterId = 3,
                            EpisodeId = 1
                        },
                        new
                        {
                            CharacterId = 3,
                            EpisodeId = 2
                        },
                        new
                        {
                            CharacterId = 3,
                            EpisodeId = 3
                        },
                        new
                        {
                            CharacterId = 4,
                            EpisodeId = 1
                        },
                        new
                        {
                            CharacterId = 4,
                            EpisodeId = 2
                        },
                        new
                        {
                            CharacterId = 4,
                            EpisodeId = 3
                        },
                        new
                        {
                            CharacterId = 7,
                            EpisodeId = 1
                        },
                        new
                        {
                            CharacterId = 5,
                            EpisodeId = 1
                        },
                        new
                        {
                            CharacterId = 5,
                            EpisodeId = 2
                        },
                        new
                        {
                            CharacterId = 5,
                            EpisodeId = 3
                        },
                        new
                        {
                            CharacterId = 6,
                            EpisodeId = 1
                        },
                        new
                        {
                            CharacterId = 6,
                            EpisodeId = 2
                        },
                        new
                        {
                            CharacterId = 6,
                            EpisodeId = 3
                        });
                });

            modelBuilder.Entity("StarWars.Domain.CharacterFriend", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterFriendId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "CharacterFriendId");

                    b.ToTable("CharacterFriend");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            CharacterFriendId = 3
                        },
                        new
                        {
                            CharacterId = 1,
                            CharacterFriendId = 4
                        },
                        new
                        {
                            CharacterId = 1,
                            CharacterFriendId = 6
                        },
                        new
                        {
                            CharacterId = 1,
                            CharacterFriendId = 5
                        },
                        new
                        {
                            CharacterId = 2,
                            CharacterFriendId = 7
                        },
                        new
                        {
                            CharacterId = 3,
                            CharacterFriendId = 1
                        },
                        new
                        {
                            CharacterId = 3,
                            CharacterFriendId = 4
                        },
                        new
                        {
                            CharacterId = 3,
                            CharacterFriendId = 6
                        },
                        new
                        {
                            CharacterId = 4,
                            CharacterFriendId = 1
                        },
                        new
                        {
                            CharacterId = 4,
                            CharacterFriendId = 3
                        },
                        new
                        {
                            CharacterId = 4,
                            CharacterFriendId = 5
                        },
                        new
                        {
                            CharacterId = 4,
                            CharacterFriendId = 6
                        },
                        new
                        {
                            CharacterId = 7,
                            CharacterFriendId = 2
                        },
                        new
                        {
                            CharacterId = 5,
                            CharacterFriendId = 1
                        },
                        new
                        {
                            CharacterId = 5,
                            CharacterFriendId = 3
                        },
                        new
                        {
                            CharacterId = 5,
                            CharacterFriendId = 4
                        },
                        new
                        {
                            CharacterId = 5,
                            CharacterFriendId = 6
                        },
                        new
                        {
                            CharacterId = 6,
                            CharacterFriendId = 1
                        },
                        new
                        {
                            CharacterId = 6,
                            CharacterFriendId = 3
                        },
                        new
                        {
                            CharacterId = 6,
                            CharacterFriendId = 4
                        });
                });

            modelBuilder.Entity("StarWars.Domain.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EpisodeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EpisodeName = "NEWHOPE"
                        },
                        new
                        {
                            Id = 2,
                            EpisodeName = "EMPIRE"
                        },
                        new
                        {
                            Id = 3,
                            EpisodeName = "JEDI"
                        });
                });

            modelBuilder.Entity("StarWars.Domain.CharacterEpisode", b =>
                {
                    b.HasOne("StarWars.Domain.Character", "Character")
                        .WithMany("CharacterEpisodes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWars.Domain.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWars.Domain.CharacterFriend", b =>
                {
                    b.HasOne("StarWars.Domain.Character", "Character")
                        .WithMany("Friends")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
